### PR TITLE
Tree experiment

### PR DESCRIPTION
**Pull request by anderejd**
Solves: #3
Solves: #2 

This is not ready to merge, I took a whole lot of liberty with this PR ~~and it is missing the commits from the last 24 hours or so~~.

The history is a bit unexpected since I merged in `cargo-tree` as boiler plate, most of it is still there. That seemed like a reasonable approach to me since `cargo-tree` already had the recursive dependency walking in place but was not packaged up as a library and needed some modifications.

Here is the current output if running `cargo osha` (after `cargo install --path . --force`) on this branch:

cargo-osha

As a side note, how about renaming to `cargo-geiger`? :) ☢️ 

Does this PR seem like a good direction at all for cargo-osha?
What should change?
What is missing?

### CODE REVIEW

**Comment by icefoxen** [comment]
Holy crap.

Are you sure you don't want to just make your own crate?  :grin:

**Comment by anderejd** [comment]
I just pushed up cherry picking form master, pretty sure it's in sync again. 

> Are you sure you don't want to just make your own crate? 😁

Maybe? If you don't think this is the direction for cargo-osha I will make a new repos and crate. I don't feel the need to have it under my github user though, it's like max 10% that's my code in this PR, the rest is the original cargo-osha on top of cargo-tree. :)

**Comment by anderejd** [comment]
Conflicts fixed. Feel free to review, merge or just close :)

**Comment by anderejd** [comment]
I did what you suggested and created a new project: https://crates.io/crates/cargo-geiger

If you want to merge the projects later that would be totally fine with me. Thanks for the nice and simple code btw! 👍 

Closing.

**Pull request closed without merging**
